[package]
name = "diesel_sqlite"
version = "0.1.0"
authors = ["mycognosist <gnomad@cryptolab.net>"]

[dependencies]
diesel = { version = "0.16.0", features = ["sqlite"] }
diesel_codegen = { version = "0.16.0", features = ["sqlite"] }
dotenv = "0.9.0"
